### ISSUE TITLE
Feature request: Format Code in right click menu

### ISSUE THREAD

**Issue by J-Siu** [ilich/vscode-cssfmt#1]
Can we have a "Format Code" entry in the right click menu?

Thank you!

**Comment by ilich** [comment]
I don't think VS Code supports context menu integration for extensions. I haven't found any information about main window menu or context menu. Please let me know if you have seen an example somewhere.

**Comment by J-Siu** [comment]
hmm, actually it does. Check out this project https://github.com/kasik96/VSCode-PHP-Format
