### ISSUE TITLE
Would you like to use CSSfmt(npm)?

### ISSUE THREAD

**Issue by msaktype** [ilich/vscode-cssfmt#2]
Hi, I'm the author of [CSSfmt](https://github.com/morishitter/cssfmt) that is implemented as a Node module.

If you don't have any reasons to create vscode-cssfmt by the own implementation, would you like to use CSSfmt?

Thanks.

**Comment by ilich** [comment]
Hi,

I have never heard about your project. It supports CSS formatting, isn't it? Does it support CSS minification? Is it possible to use your tool as a library?

If it is a library and it can do compress/format then I am happy to accept your pull request. You can put your changes to the project.

Unfortunately I do not have time to do the enhancement on my own.

Thanks you for your interest to the project!

**Comment by ilich** [comment]
Please send me the pull request, and I will publish an update to VS marketplace.

Thanks.
